### PR TITLE
Improve stability with latest VS Code

### PR DESCRIPTION
**Pull request by deitry**
Hi
Both current 2.7.5 version of extension in Marketplace and 3.0.0 built from sources fails and disconnects too often. With these changes extension is working much more stable with latest VS Code 1.48 Insiders and Unity 2019.4.1f on Windows 10. 

I didn't test it with other versions of Unity and other OSes and also I couldn't manage tests to work due to linking errors. I hope it doesn't break anything too much since there are no significant changes to code.

### CODE REVIEW

**Comment by deitry** [comment]
I tried to install version with proposed changes to another computer with latest Stable version of VS Code and slightly different configuration, I discover that extension did not run properly due to lacking `vscode-nls` module in runtime which is referenced from `MonoDebug\src\typescript\extension.ts`.

After moving `vscode-nls` from `devDependencies` to `dependencies` in `package.json` extension seems to be working fine.

**Comment by brokenbeta** [comment]
I gave this version a try against Unity 2019.4.2f1 (on Windows 10) and for me it's _way_ more stable than the currently published version. Thank you @deitry for looking into this.

**Review by miniwolf — APPROVED** [review]

**Review by andersonlcramos — APPROVED** [review]

**Comment by TCROC** [comment]
I would very much like to try this build, but am not sure how to build it.  Can someone provide some instructions on how to do this?  Thanks.

**Comment by deitry** [comment]
There is small instruction at the bottom of README.md in the root of the repo:
```
git clone https://github.com/Unity-Technologies/vscode-unity-debug
cd vscode-unity-debug
git submodule update --init --recursive
```

If some tests projects will not be built, that is OK.
After you done with building UnityDebug project, you have to create .vsix package

**Comment by TCROC** [comment]
@deitry Awesome thanks!  There is one more step before the ``vsce package`` command.  I also had to run ``npm install``.  Then everything worked correctly.

On another note, do you plan on maintaining your fork?

**Comment by miniwolf** [comment]
If we can merge this into master, then I will get this published so everyone can benefit from this release.

**Comment by TCROC** [comment]
@miniwolf That would be awesome!  It's been extremely useful.

**Comment by miniwolf** [comment]
I will go make sure to do this tomorrow at work.

**Comment by TCROC** [comment]
Awesome!  Thanks @miniwolf !

**Pull request merged**
