### PR TITLE
Support for hovering on variables

### LINKED ISSUE #23: Hovering on anything other than method argument doesn't show variable value popup
**Steps**:

1. Set a breakpoint
2. Try to hover mouse on some object's member
3. Popup doesn't appear

**Expected results**: popup with variable value should appear

### PR DESCRIPTION
**Pull request by JohnPoison**
Previously hovering worked only for method's arguments.
It seems that hovering works now for every variable.

I had to write a little workaround for this's members.

It should fix #23 #15

### CODE REVIEW

**Comment by lukaszunity** [comment]
I tried to make similar change myself. There are a lot of scenarios where this does not work. From memory, here is one case that does not work.

`if(value != 0 && value2 > 0)` 

If you hover over `value2`, then I think you get the entire substring `if(value != 0 && value2` as the expression to evaluate.

I would rather not add this, as there will be a endless list of cases where it does not work properly and I would rather that this would be fixed in VS Code by it only sending legal values for evaluation to the debugger extension.

**Comment by JohnPoison** [comment]
@lukaszunity your test case works absolutely fine. And even more complex test cases are working for me. I've tried this fix in my daily work and find it useful. VSCode gives appropriate strings to evaluation.

If something doesn't work, this extension won't crash. Nothing bad happens. When VSCode fix something, it would work automatically, because code already supports it.

**Comment by lukaszunity** [comment]
Well then, maybe they fixed it since last time I tried it. I will find some time to test this soon.

**Comment by JohnPoison** [comment]
I find the issue that evaluation of expressions doesn't work when you're going up to the stack. It also doesn't work in "Watch" pane. Any ideas on how to fix that?

**Comment by lukaszunity** [comment]
> Any ideas on how to fix that?

Not immediately. Will have a look when I find the time.

**Comment by cyrax1800** [comment]
when this pull request is going be merge?
I really need this feature.. Thanks..

**Comment by JimmyDeemo** [comment]
Cross posting here to mention that there is an issue on the VSCode Github for this feature. https://github.com/Microsoft/vscode/issues/6042

In theory enabling the 'supportsEvaluateForHovers' capability would enable. Any updates on this would be great.

**Comment by kwasak** [comment]
+1 I also really need this feature!

**Comment by epicsquad** [comment]
I've updated extension to version 1.2.0 but hovering on variables still not working, is it okay or i need something to do to enable this feature?

**Pull request merged**
